services:
  astron:
    build:
      context: ../..
      dockerfile: launch/docker/astron.dockerfile
    ports:
      - "7198:7198"
    volumes:
      - "../..:/app/game"

  uberdog:
    depends_on:
      - astron
    image: ttap-server
    pull_policy: never
    build:
      context: ../..
      dockerfile: launch/docker/server.dockerfile
    environment:
      SERVICE_TO_RUN: UD
      BASE_CHANNEL: 1000000
      MAX_CHANNELS: 999999
      STATESERVER: 4002
      ASTRON_IP: astron:7199
      EVENTLOGGER_IP: astron:7197
    volumes:
      - "../..:/app"

  ai:
    depends_on:
      - astron
      - uberdog
    image: ttap-server
    pull_policy: never
    environment:
      SERVICE_TO_RUN: AI
      BASE_CHANNEL: 401000000
      MAX_CHANNELS: 999999
      STATESERVER: 4002
      ASTRON_IP: astron:7199
      EVENTLOGGER_IP: astron:7197
      DISTRICT_NAME: "Archipelago Avenue"
    volumes:
      - "../..:/app"
